# Generated by Django 5.2 on 2025-05-01 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectName", models.CharField(max_length=200)),
                ("projectImage", models.DateTimeField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="DetailProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectContent", models.CharField(max_length=1000)),
                (
                    "projectId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.allproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reivew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectReviewStar", models.IntegerField()),
                ("userName", models.CharField(max_length=10)),
                ("projectReviewContent", models.CharField(max_length=1000)),
                (
                    "projectId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.allproject",
                    ),
                ),
            ],
        ),
    ]
