# Generated by Django 5.2 on 2025-05-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="allproject",
            old_name="projectImage",
            new_name="projectDate",
        ),
    ]
