# Generated by Django 5.2 on 2025-05-01 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_alter_user_userid"),
        ("project", "0002_rename_projectimage_allproject_projectdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="allproject",
            name="projectUserName",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.user",
                to_field="userId",
            ),
        ),
    ]
